name: CI de Verificação - GitFlow Master

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verificação de Sintaxe (Lint)
        run: |
          # Este comando checa se o seu código Flask tem erros básicos
          python -m py_compile app/blueprints/web.py run.py
