name: CI de Verificação - GitFlow Master

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          # Alterado para 3.11 para alinhar com o seu deploy no PythonAnywhere
          python-version: "3.11"

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          # Garante que as dependências base existam mesmo se o requirements estiver incompleto
          pip install flask gunicorn 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Verificação de Sintaxe (Lint)
        run: |
          # Adicionei o caminho completo para evitar erro de 'file not found'
          python -m py_compile run.py
          # Verifica a pasta app recursivamente
          python -m compileall app/
      # ... (mantenha os passos anteriores)
      - name: Deploy automático no PythonAnywhere
        if: github.ref == 'refs/heads/main' # Só faz deploy se for a branch main
        env:
          PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
          PA_USERNAME: ${{ secrets.PA_USERNAME }}
        run: |
          # Este comando avisa o PythonAnywhere para dar um git pull e fazer o reload
          curl -X POST "https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/webapps/almeida.pythonanywhere.com/reload/" \
            -H "Authorization: Token $PA_API_TOKEN"
